version: '3'

services:
  frontend:
    build: ./frontend
    image: app/frontend:latest
    ports:
      - "80:80"
    restart: always

  backend:
    build: ./backend
    image: app/backend:latest
    ports:
      - "8080:8080"
    restart: always
