name: Build, Deploy and Test with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker compose build

      - name: Save Docker images
        run: |
          docker save app/frontend:latest -o frontend.tar  
          docker save app/backend:latest -o backend.tar

      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            frontend.tar
            backend.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker images artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./docker-images
          
      - name: list
        run: ls -la
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}          
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo mkdir -p /app
            sudo scp docker-images/frontend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/app
            sudo scp docker-images/backend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/app

            sudo ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker load < /app/frontend.tar"
            sudo ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker load < /app/backend.tar"

            cd /app
            sudo docker-compose up -d
