name: Build, Deploy and Test with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Save Docker images
        run: |
          docker save frontend > frontend.tar
          docker save backend > backend.tar

      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            frontend.tar
            backend.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Docker images artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./docker-images

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /app
            scp frontend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/app
            scp backend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/app

            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker load < /app/frontend.tar"
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker load < /app/backend.tar"

            cd /app
            docker-compose up -d
